#!/bin/bash

args=("$@")

cd /users/ecologie/abs/spatial-PDMP-pairwise-contest/result/

#description of arguments in main.cpp
time  executable.out ${args[0]} ${args[1]} ${args[2]} ${args[3]} ${args[4]} ${args[5]} ${args[6]} ${args[7]} ${args[8]} ${args[9]} ${args[10]} ${args[11]} ${args[12]} ${args[13]} ${args[14]} ${args[15]} ${args[16]} ${args[17]} ${args[18]}



