#!/bin/csh

cd ./result

date
g++ -o exe.out ../creationScores.cpp
#1st argument has to be lower than minimal clusterID
#2nd argument has to be higher than maximal clusterID
#3rd argument has to be higher than number of jobs
time ./exe.out 1400 1401 50
date



