#!/bin/csh

# pour lancer le script: bash script
# deuxieme methode: le rendre executable : chmod u+x script ; puis executer: ./script


cd ./result

date
g++ -o exe.out ../creationScores.cpp
time ./exe.out 1400 1401 50
date



