#!/bin/bash

# pour lancer le script: bash script
# deuxieme methode: le rendre executable : chmod u+x script ; puis executer: ./script


# ID cluster, ID job, taille du reseau (L), phi resident (phi1), phi mutant (phi2), K, nbrInitial de cases avec mutant, N, timeMax, diffusionD, probaMoving

args=("$@")

cd /users/ecologie/abs/2019072203_eq11/result/

time  executable.out ${args[0]} ${args[1]} ${args[2]} ${args[3]} ${args[4]} ${args[5]} ${args[6]} ${args[7]} ${args[8]} ${args[9]} ${args[10]} ${args[11]} ${args[12]} ${args[13]} ${args[14]} ${args[15]} ${args[16]} ${args[17]} ${args[18]}



